displayName: Client Certificate CN Authorization
summary: Authorize requests based on the TLS client certificate Common Name (CN)
type: middleware

import: github.com/wartydany/traefik-cn-authz

testData:
  regex: "^example\\.org$"
